name: Ruby CI

on:
  push:
    branches: # Runs on all branches
      - '*'
  pull_request:
    branches: # Runs on all pull requests
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.6' # Adjust to your Ruby version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up database
        run: |
          cp config/database.yml.ci config/database.yml || echo 'No custom database.yml.ci provided'
          RAILS_ENV=test bin/rails db:create
          RAILS_ENV=test bin/rails db:schema:load


      - name: Run tests
        run: bin/rails test